"""Add feeds models

Revision ID: 83ef337c8e34
Revises: 
Create Date: 2020-09-14 17:17:52.699181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "83ef337c8e34"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feeds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("properties", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feeds")),
        sa.UniqueConstraint("url", name=op.f("uq_feeds_url")),
    )
    op.create_table(
        "feed_archive_pages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("feed_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["feed_id"],
            ["feeds.id"],
            name=op.f("fk_feed_archive_pages_feed_id_feeds"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feed_archive_pages")),
        sa.UniqueConstraint(
            "feed_id", "order", name=op.f("uq_feed_archive_pages_feed_id")
        ),
        sa.UniqueConstraint("url", "feed_id", name=op.f("uq_feed_archive_pages_url")),
    )
    op.create_table(
        "feed_page_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("archive_page_id", sa.Integer(), nullable=False),
        sa.Column("guid", sa.Text(), nullable=False),
        sa.Column("title", sa.UnicodeText(), nullable=False),
        sa.Column("link", sa.Text(), nullable=False),
        sa.Column("published", sa.DateTime(), nullable=False),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["archive_page_id"],
            ["feed_archive_pages.id"],
            name=op.f("fk_feed_page_entries_archive_page_id_feed_archive_pages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feed_page_entries")),
        sa.UniqueConstraint(
            "archive_page_id", "guid", name=op.f("uq_feed_page_entries_archive_page_id")
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feed_page_entries")
    op.drop_table("feed_archive_pages")
    op.drop_table("feeds")
    # ### end Alembic commands ###
